name: Docker CI

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/kundanutkarsha/docker-learning:latest -t ghcr.io/kundanutkarsha/docker-learning:${{ github.sha }} .

      - name: Run container
        run: |
          docker run -d --name my-first-app-test -p 8000:8000 ghcr.io/kundanutkarsha/docker-learning:latest
          sleep 5
          curl http://localhost:8000
          docker rm -f my-first-app-test

      - name: Push Docker image
        run: |
          docker push ghcr.io/kundanutkarsha/docker-learning:latest
          docker push ghcr.io/kundanutkarsha/docker-learning:${{ github.sha }}
